
velocity_finger_trajectory_controller:
    constraints:
      goal_time: 1.0
      mico_joint_finger_1: &joint_constraints {goal: 0.02, trajectory: 0.05}
      mico_joint_finger_2: *joint_constraints
      stopped_velocity_tolerance: 0.02
    gains:
      mico_joint_finger_1: &finger_joint_gains {p: 10, i: 0.0, d: 0.0, i_clamp: 1.0}
      mico_joint_finger_2: *finger_joint_gains
    joints:
      - mico_joint_finger_1
      - mico_joint_finger_2
    type: velocity_controllers/JointTrajectoryController

velocity_joint_trajectory_controller:
    constraints:
      goal_time: 1.0
      mico_joint_1: *joint_constraints #{goal: 0.02, trajectory: 0.05}
      mico_joint_2: *joint_constraints
      mico_joint_3: *joint_constraints
      mico_joint_4: *joint_constraints
      mico_joint_5: *joint_constraints
      mico_joint_6: *joint_constraints
      stopped_velocity_tolerance: 0.02
    gains:
      mico_joint_1: &mico_joint_gains1 { p: 500.0, i: 0.0, d: 0.0, i_clamp: 10.0 }
      mico_joint_2: *mico_joint_gains1
      mico_joint_3: *mico_joint_gains1
      mico_joint_4: &mico_joint_gains2 { p: 300.0, i: 0.0, d: 0.0, i_clamp: 5.0 }
      mico_joint_5: *mico_joint_gains2
      mico_joint_6: *mico_joint_gains2
    joints:
    - mico_joint_1
    - mico_joint_2
    - mico_joint_3
    - mico_joint_4
    - mico_joint_5
    - mico_joint_6
    type: velocity_controllers/JointTrajectoryController

joint_state_controller:
  publish_rate: 100
  type: joint_state_controller/JointStateController

effort_finger_trajectory_controller:
    constraints:
      goal_time: 1.0
      mico_joint_finger_1: *joint_constraints #{goal: 0.02, trajectory: 0.05}
      mico_joint_finger_2: *joint_constraints
      stopped_velocity_tolerance: 0.02
    gains:
      mico_joint_finger_1: &effort_finger_joint_gains {p: 50, i: 0.0, d: 0.0, i_clamp: 1.0}
      mico_joint_finger_2: *effort_finger_joint_gains
    joints:
    - mico_joint_finger_1
    - mico_joint_finger_2
    type: effort_controllers/JointTrajectoryController

effort_joint_trajectory_controller:
    constraints:
      goal_time: 1.0
      mico_joint_1: *joint_constraints #{goal: 0.02, trajectory: 0.05}
      mico_joint_2: *joint_constraints
      mico_joint_3: *joint_constraints
      mico_joint_4: *joint_constraints
      mico_joint_5: *joint_constraints
      mico_joint_6: *joint_constraints
      stopped_velocity_tolerance: 0.02
    gains:
      mico_joint_1: &mico_effort_joint_gains1 { p: 5000.0, i: 0.0, d: 0.0, i_clamp: 10.0 }
      mico_joint_2: *mico_effort_joint_gains1
      mico_joint_3: *mico_effort_joint_gains1
      mico_joint_4: &mico_effort_joint_gains2 { p: 500.0, i: 0.0, d: 0.0, i_clamp: 5.0 }
      mico_joint_5: *mico_effort_joint_gains2
      mico_joint_6: *mico_effort_joint_gains2
    joints:
    - mico_joint_1
    - mico_joint_2
    - mico_joint_3
    - mico_joint_4
    - mico_joint_5
    - mico_joint_6
    type: effort_controllers/JointTrajectoryController

# -------------------- #
# POSITION CONTROLLERS #
# -------------------- #

finger_1_position_controller:
    joint: mico_joint_finger_1
    pid: {p: 10, i: 0, d: 0}
    type: velocity_controllers/JointPositionController

finger_2_position_controller:
    joint: mico_joint_finger_2
    pid: {p: 10, i: 0, d: 0}
    type: velocity_controllers/JointPositionController

joint_1_position_controller:
    joint: mico_joint_1
    pid: {p: 500, i: 0, d: 0}
    type: velocity_controllers/JointPositionController

joint_2_position_controller:
    joint: mico_joint_2
    pid: {p: 500, i: 0, d: 0}
    type: velocity_controllers/JointPositionController

joint_3_position_controller:
    joint: mico_joint_3
    pid: {p: 500, i: 0, d: 0}
    type: velocity_controllers/JointPositionController

joint_4_position_controller:
    joint: mico_joint_4
    pid: {p: 300, i: 0, d: 0}
    type: velocity_controllers/JointPositionController

joint_5_position_controller:
    joint: mico_joint_5
    pid: {p: 300, i: 0, d: 0}
    type: velocity_controllers/JointPositionController

joint_6_position_controller:
    joint: mico_joint_6
    pid: {p: 300, i: 0, d: 0}
    type: velocity_controllers/JointPositionController


# -------------------- #
# VELOCITY CONTROLLERS #
# -------------------- #

finger_1_velocity_controller:
    joint: mico_joint_finger_1
    pid:
      d: 0
      i: 0
      p: 10
    type: effort_controllers/JointVelocityController

finger_2_velocity_controller:
    joint: mico_joint_finger_2
    pid:
      d: 0
      i: 0
      p: 10
    type: effort_controllers/JointVelocityController

joint_1_velocity_controller:
    joint: mico_joint_1
    pid:
      d: 0
      i: 0
      p: 5000
    type: effort_controllers/JointVelocityController

joint_2_velocity_controller:
    joint: mico_joint_2
    pid:
      d: 0
      i: 0
      p: 5000
    type: effort_controllers/JointVelocityController

joint_3_velocity_controller:
    joint: mico_joint_3
    pid:
      d: 0
      i: 0
      p: 5000
    type: effort_controllers/JointVelocityController

joint_4_velocity_controller:
    joint: mico_joint_4
    pid:
      d: 0
      i: 0
      p: 500
    type: effort_controllers/JointVelocityController

joint_5_velocity_controller:
    joint: mico_joint_5
    pid:
      d: 0
      i: 0
      p: 200
    type: effort_controllers/JointVelocityController

joint_6_velocity_controller:
    joint: mico_joint_6
    pid:
      d: 0
      i: 0
      p: 500
    type: effort_controllers/JointVelocityController

