
velocity_finger_trajectory_controller:
    constraints:
      goal_time: 1.0
      $(arg prefix)mico_joint_finger_1: &joint_constraints {goal: 0.02, trajectory: 0.05}
      $(arg prefix)mico_joint_finger_2: *joint_constraints
      stopped_velocity_tolerance: 0.02
    gains:
      $(arg prefix)mico_joint_finger_1: &finger_joint_gains {p: 10, i: 0.0, d: 0.1, i_clamp: 1.0}
      $(arg prefix)mico_joint_finger_2: *finger_joint_gains
    joints:
      - $(arg prefix)mico_joint_finger_1
      - $(arg prefix)mico_joint_finger_2
    type: velocity_controllers/JointTrajectoryController

velocity_joint_trajectory_controller:
    constraints:
      goal_time: 1.0
      $(arg prefix)mico_joint_1: *joint_constraints #{goal: 0.02, trajectory: 0.05}
      $(arg prefix)mico_joint_2: *joint_constraints
      $(arg prefix)mico_joint_3: *joint_constraints
      $(arg prefix)mico_joint_4: *joint_constraints
      $(arg prefix)mico_joint_5: *joint_constraints
      $(arg prefix)mico_joint_6: *joint_constraints
      stopped_velocity_tolerance: 0.02
    gains:
      $(arg prefix)mico_joint_1: &mico_joint_gains1 { p: 1000.0, i: 0.0, d: 0.5, i_clamp: 10.0 }
      $(arg prefix)mico_joint_2: *mico_joint_gains1
      $(arg prefix)mico_joint_3: *mico_joint_gains1
      $(arg prefix)mico_joint_4: &mico_joint_gains2 { p: 500.0, i: 0.0, d: 0.5, i_clamp: 5.0 }
      $(arg prefix)mico_joint_5: *mico_joint_gains2
      $(arg prefix)mico_joint_6: *mico_joint_gains2
    joints:
    - $(arg prefix)mico_joint_1
    - $(arg prefix)mico_joint_2
    - $(arg prefix)mico_joint_3
    - $(arg prefix)mico_joint_4
    - $(arg prefix)mico_joint_5
    - $(arg prefix)mico_joint_6
    type: velocity_controllers/JointTrajectoryController

joint_state_controller:
  publish_rate: 100
  type: joint_state_controller/JointStateController

effort_finger_trajectory_controller:
    constraints:
      goal_time: 1.0
      $(arg prefix)mico_joint_finger_1: *joint_constraints #{goal: 0.02, trajectory: 0.05}
      $(arg prefix)mico_joint_finger_2: *joint_constraints
      stopped_velocity_tolerance: 0.02
    gains:
      $(arg prefix)mico_joint_finger_1: &effort_finger_joint_gains {p: 50, i: 0.0, d: 0.1, i_clamp: 1.0}
      $(arg prefix)mico_joint_finger_2: *effort_finger_joint_gains
    joints:
    - $(arg prefix)mico_joint_finger_1
    - $(arg prefix)mico_joint_finger_2
    type: effort_controllers/JointTrajectoryController

effort_joint_trajectory_controller:
    constraints:
      goal_time: 1.0
      $(arg prefix)mico_joint_1: *joint_constraints #{goal: 0.02, trajectory: 0.05}
      $(arg prefix)mico_joint_2: *joint_constraints
      $(arg prefix)mico_joint_3: *joint_constraints
      $(arg prefix)mico_joint_4: *joint_constraints
      $(arg prefix)mico_joint_5: *joint_constraints
      $(arg prefix)mico_joint_6: *joint_constraints
      stopped_velocity_tolerance: 0.02
    gains:
      $(arg prefix)mico_joint_1: &mico_effort_joint_gains1 { p: 5000.0, i: 0.0, d: 0.5, i_clamp: 10.0 }
      $(arg prefix)mico_joint_2: *mico_effort_joint_gains1
      $(arg prefix)mico_joint_3: *mico_effort_joint_gains1
      $(arg prefix)mico_joint_4: &mico_effort_joint_gains2 { p: 500.0, i: 0.0, d: 0.5, i_clamp: 10.0 }
      $(arg prefix)mico_joint_5: *mico_effort_joint_gains2
      $(arg prefix)mico_joint_6: *mico_effort_joint_gains2
    joints:
    - $(arg prefix)mico_joint_1
    - $(arg prefix)mico_joint_2
    - $(arg prefix)mico_joint_3
    - $(arg prefix)mico_joint_4
    - $(arg prefix)mico_joint_5
    - $(arg prefix)mico_joint_6
    type: effort_controllers/JointTrajectoryController

# platform_virtual_joint_controller:
#     constraints:
#       goal_time: 1.0
#       $(arg prefix)platform_prismatic_x: *joint_constraints
#       $(arg prefix)platform_prismatic_y: *joint_constraints
#       $(arg prefix)platform_continuous_z: *joint_constraints
#       stopped_velocity_tolerance: 0.02
#     gains:
#       $(arg prefix)platform_prismatic_x: &joint_gains1 { p: 1.0, i: 0.0, d: 0.0, i_clamp: 10.0 }
#       $(arg prefix)platform_prismatic_y: *joint_gains1
#       $(arg prefix)platform_continuous_z: *joint_gains1
#     joints:
#       - $(arg prefix)platform_prismatic_x
#       - $(arg prefix)platform_prismatic_y
#       - $(arg prefix)platform_continuous_z
#     type: position_controllers/JointTrajectoryController

# -------------------- #
# POSITION CONTROLLERS #
# -------------------- #

finger_1_position_controller:
    joint: $(arg prefix)mico_joint_finger_1
    pid: {p: 10, i: 0, d: 0.1}
    type: velocity_controllers/JointPositionController

finger_2_position_controller:
    joint: $(arg prefix)mico_joint_finger_2
    pid: {p: 10, i: 0, d: 0.1}
    type: velocity_controllers/JointPositionController

joint_1_position_controller:
    joint: $(arg prefix)mico_joint_1
    pid: {p: 500, i: 0, d: 0.5}
    type: velocity_controllers/JointPositionController

joint_2_position_controller:
    joint: $(arg prefix)mico_joint_2
    pid: {p: 500, i: 0, d: 0.5}
    type: velocity_controllers/JointPositionController

joint_3_position_controller:
    joint: $(arg prefix)mico_joint_3
    pid: {p: 500, i: 0, d: 0.5}
    type: velocity_controllers/JointPositionController

joint_4_position_controller:
    joint: $(arg prefix)mico_joint_4
    pid: {p: 300, i: 0, d: 0.5}
    type: velocity_controllers/JointPositionController

joint_5_position_controller:
    joint: $(arg prefix)mico_joint_5
    pid: {p: 300, i: 0, d: 0.5}
    type: velocity_controllers/JointPositionController

joint_6_position_controller:
    joint: $(arg prefix)mico_joint_6
    pid: {p: 300, i: 0, d: 0.5}
    type: velocity_controllers/JointPositionController


# -------------------- #
# VELOCITY CONTROLLERS #
# -------------------- #

finger_1_velocity_controller:
    joint: $(arg prefix)mico_joint_finger_1
    pid:
      d: 0
      i: 0
      p: 10
    type: effort_controllers/JointVelocityController

finger_2_velocity_controller:
    joint: $(arg prefix)mico_joint_finger_2
    pid:
      d: 0
      i: 0
      p: 10
    type: effort_controllers/JointVelocityController

joint_1_velocity_controller:
    joint: $(arg prefix)mico_joint_1
    pid:
      d: 0
      i: 0
      p: 5000
    type: effort_controllers/JointVelocityController

joint_2_velocity_controller:
    joint: $(arg prefix)mico_joint_2
    pid:
      d: 0
      i: 0
      p: 5000
    type: effort_controllers/JointVelocityController

joint_3_velocity_controller:
    joint: $(arg prefix)mico_joint_3
    pid:
      d: 0
      i: 0
      p: 5000
    type: effort_controllers/JointVelocityController

joint_4_velocity_controller:
    joint: $(arg prefix)mico_joint_4
    pid:
      d: 0
      i: 0
      p: 500
    type: effort_controllers/JointVelocityController

joint_5_velocity_controller:
    joint: $(arg prefix)mico_joint_5
    pid:
      d: 0
      i: 0
      p: 200
    type: effort_controllers/JointVelocityController

joint_6_velocity_controller:
    joint: $(arg prefix)mico_joint_6
    pid:
      d: 0
      i: 0
      p: 500
    type: effort_controllers/JointVelocityController

