# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - summit_virtual_joint
    - mico_joint_1
    - mico_joint_2
    - mico_joint_3
    - mico_joint_4
    - mico_joint_5
    - mico_joint_6
    - mico_joint_finger_1
    - mico_joint_finger_2
    - joint_back_left_wheel
    - joint_back_right_wheel
    - joint_front_left_wheel
    - joint_front_right_wheel
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
# mico:
#   joint_state_controller:
#     type: joint_state_controller/JointStateController
#     publish_rate: 50
controller_list:
  - name: velocity_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - mico_joint_1
      - mico_joint_2
      - mico_joint_3
      - mico_joint_4
      - mico_joint_5
      - mico_joint_6
  - name: velocity_finger_trajectory_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - mico_joint_finger_1
      - mico_joint_finger_2