<?xml version="1.0"?>
<!-- m1_6n refers to mico v1 6DOF non-spherical -->


<root xmlns:xi="http://www.w3.org/2001/XInclude" 
    xmlns:gazebo="http://playerstage.sourceforge.net/gazebo/xmlschema/#gz" 
    xmlns:model="http://playerstage.sourceforge.net/gazebo/xmlschema/#model" 
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor" 
    xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body" 
    xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom" 
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller" 
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface" 
    xmlns:rendering="http://playerstage.sourceforge.net/gazebo/xmlschema/#rendering" 
    xmlns:renderable="http://playerstage.sourceforge.net/gazebo/xmlschema/#renderable" 
    xmlns:physics="http://playerstage.sourceforge.net/gazebo/xmlschema/#physics" 
    xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find mico_description)/urdf/kinova_common.xacro" />
    <xacro:include filename="$(find mico_description)/urdf/kinova_finger_set.xacro" />

    <!-- Import all Gazebo-customization elements -->
    <xacro:include filename="$(find mico_description)/urdf/kinova.gazebo" />

    <!-- Import all Kinova Mico Arm Properties elements -->
    <xacro:include filename="$(find mico_description)/urdf/micoproperties.xacro" />


    <xacro:macro name="mico2fingers" params="base_parent robot_control_ns:='' prefix:='mico' interface:=velocity color:='None' J1_offset:=0.0 J2_offset:=0.0 J3_offset:=0.0 J4_offset:=0.0 J5_offset:=0.0 J6_offset:=0.0 gazebo_ros_control:=true">

        <xacro:if value="${gazebo_ros_control}">
            <xacro:gazebo_config robot_namespace="${robot_control_ns}"/>
        </xacro:if>


        <xacro:kinova_armlink link_name="${prefix}_link_base" link_mesh="${link_base_mesh}" mesh_no="${link_base_mesh_no}"/>
        <xacro:kinova_armjoint joint_name="${prefix}_joint_base" type="${joint_base_type}" parent="${base_parent}" child="${prefix}_link_base" joint_axis_xyz="${joint_base_axis_xyz}" joint_origin_xyz="${joint_base_origin_xyz}" joint_origin_rpy="${joint_base_origin_rpy}" joint_lower_limit="0" joint_upper_limit="0" joint_velocity_limit="0" joint_torque_limit="0" fixed="true"/>

        <xacro:kinova_armlink link_name="${prefix}_link_1" link_mesh="${link_1_mesh}" use_ring_mesh="true" mesh_no="${link_1_mesh_no}"/>
        <xacro:if value="${J1_offset in [0.0, 0, None]}">
            <xacro:kinova_armjoint joint_name="${prefix}_joint_1" type="${joint_1_type}" parent="${prefix}_link_base" child="${prefix}_link_1" joint_axis_xyz="${joint_1_axis_xyz}" joint_origin_xyz="${joint_1_origin_xyz}" joint_origin_rpy="${joint_1_origin_rpy}" joint_lower_limit="${joint_1_lower_limit}" joint_upper_limit="${joint_1_upper_limit}" joint_velocity_limit="${joint_1_velocity_limit}" joint_torque_limit="${joint_1_torque_limit}" interface="${interface}"/>
        </xacro:if>
        <xacro:unless value="${J1_offset in [0.0, 0, None]}">
            <xacro:kinova_armjoint joint_name="${prefix}_joint_1" type="${joint_1_type}" parent="${prefix}_link_base" child="${prefix}_link_1" joint_axis_xyz="${joint_1_axis_xyz}" joint_origin_xyz="${joint_1_origin_xyz}" joint_origin_rpy="0 ${J_PI} ${J1_offset}" joint_lower_limit="${joint_1_lower_limit-J1_offset}" joint_upper_limit="${joint_1_upper_limit-J1_offset}" joint_velocity_limit="${joint_1_velocity_limit}" joint_torque_limit="${joint_1_torque_limit}" interface="${interface}"/>
        </xacro:unless>


        <xacro:kinova_armlink link_name="${prefix}_link_2" link_mesh="${link_2_mesh}" use_ring_mesh="true" mesh_no="${link_2_mesh_no}"/>
        <xacro:if value="${J2_offset in [0.0, 0, None]}">
            <xacro:kinova_armjoint joint_name="${prefix}_joint_2" type="${joint_2_type}" parent="${prefix}_link_1" child="${prefix}_link_2" joint_axis_xyz="${joint_2_axis_xyz}" joint_origin_xyz="${joint_2_origin_xyz}" joint_origin_rpy="${joint_2_origin_rpy}" joint_lower_limit="${joint_2_lower_limit}" joint_upper_limit="${joint_2_upper_limit}" joint_velocity_limit="${joint_2_velocity_limit}" joint_torque_limit="${joint_2_torque_limit}" interface="${interface}"/>
        </xacro:if>
        <xacro:unless value="${J2_offset in [0.0, 0, None]}">
            <xacro:kinova_armjoint joint_name="${prefix}_joint_2" type="${joint_2_type}" parent="${prefix}_link_1" child="${prefix}_link_2" joint_axis_xyz="${joint_2_axis_xyz}" joint_origin_xyz="${joint_2_origin_xyz}" joint_origin_rpy="${-J_PI/2} ${J2_offset} ${J_PI}" joint_lower_limit="${joint_2_lower_limit-J2_offset}" joint_upper_limit="${joint_2_upper_limit-J2_offset}" joint_velocity_limit="${joint_2_velocity_limit}" joint_torque_limit="${joint_2_torque_limit}" interface="${interface}"/>
        </xacro:unless>

        <xacro:kinova_armlink link_name="${prefix}_link_3" link_mesh="${link_3_mesh}" use_ring_mesh="true" mesh_no="${link_3_mesh_no}"/>
        <xacro:if value="${J3_offset in [0.0, 0, None]}">
            <xacro:kinova_armjoint joint_name="${prefix}_joint_3" type="${joint_3_type}" parent="${prefix}_link_2" child="${prefix}_link_3" joint_axis_xyz="${joint_3_axis_xyz}" joint_origin_xyz="${joint_3_origin_xyz}" joint_origin_rpy="${joint_3_origin_rpy}" joint_lower_limit="${joint_3_lower_limit}" joint_upper_limit="${joint_3_upper_limit}" joint_velocity_limit="${joint_3_velocity_limit}" joint_torque_limit="${joint_3_torque_limit}" interface="${interface}"/>
        </xacro:if>
        <xacro:unless value="${J3_offset in [0.0, 0, None]}">
            <xacro:kinova_armjoint joint_name="${prefix}_joint_3" type="${joint_3_type}" parent="${prefix}_link_2" child="${prefix}_link_3" joint_axis_xyz="${joint_3_axis_xyz}" joint_origin_xyz="${joint_3_origin_xyz}" joint_origin_rpy="0 ${J_PI} ${J3_offset}" joint_lower_limit="${joint_3_lower_limit-J3_offset}" joint_upper_limit="${joint_3_upper_limit-J3_offset}" joint_velocity_limit="${joint_3_velocity_limit}" joint_torque_limit="${joint_3_torque_limit}" interface="${interface}"/>
        </xacro:unless>


        <xacro:kinova_armlink link_name="${prefix}_link_4" link_mesh="${link_4_mesh}" use_ring_mesh="true" ring_mesh="ring_small" mesh_no="${link_4_mesh_no}"/>
        <xacro:if value="${J4_offset in [0.0, 0, None]}">
            <xacro:kinova_armjoint joint_name="${prefix}_joint_4" type="${joint_4_type}" parent="${prefix}_link_3" child="${prefix}_link_4" joint_axis_xyz="${joint_4_axis_xyz}" joint_origin_xyz="${joint_4_origin_xyz}" joint_origin_rpy="${joint_4_origin_rpy}" joint_lower_limit="${joint_4_lower_limit-J4_offset}" joint_upper_limit="${joint_4_upper_limit-J4_offset}" joint_velocity_limit="${joint_4_velocity_limit}" joint_torque_limit="${joint_4_torque_limit}" interface="${interface}"/>
        </xacro:if>
        <xacro:unless value="${J4_offset in [0.0, 0, None]}">
            <xacro:kinova_armjoint joint_name="${prefix}_joint_4" type="${joint_4_type}" parent="${prefix}_link_3" child="${prefix}_link_4" joint_axis_xyz="${joint_4_axis_xyz}" joint_origin_xyz="${joint_4_origin_xyz}" joint_origin_rpy="${-J_PI/2} ${J4_offset} ${J_PI}" joint_lower_limit="${joint_4_lower_limit-J4_offset}" joint_upper_limit="${joint_4_upper_limit-J4_offset}" joint_velocity_limit="${joint_4_velocity_limit}" joint_torque_limit="${joint_4_torque_limit}" interface="${interface}"/>
        </xacro:unless>

        <xacro:if value="${J5_offset in [0.0, 0, None]}">
            <xacro:kinova_armlink link_name="${prefix}_link_5" link_mesh="${link_5_mesh}" use_ring_mesh="true" ring_mesh="ring_small" mesh_no="${link_5_mesh_no}"/>
            <xacro:kinova_armjoint joint_name="${prefix}_joint_5" type="${joint_5_type}" parent="${prefix}_link_4" child="${prefix}_link_5" joint_axis_xyz="${joint_5_axis_xyz}" joint_origin_xyz="${joint_5_origin_xyz}" joint_origin_rpy="${joint_5_origin_rpy}" joint_lower_limit="${joint_5_lower_limit}" joint_upper_limit="${joint_5_upper_limit}" joint_velocity_limit="${joint_5_velocity_limit}" joint_torque_limit="${joint_5_torque_limit}" interface="${interface}"/>
        </xacro:if>

        <xacro:unless value="${J5_offset in [0.0, 0, None]}">
            <xacro:kinova_armlink link_name="${prefix}_virtual_link_5" link_mesh="None" use_ring_mesh="true" ring_mesh="ring_small" mesh_no="${link_5_mesh_no}"/>
            <xacro:kinova_armjoint joint_name="${prefix}_joint_4_to_5" type="fixed" parent="${prefix}_link_4" child="${prefix}_virtual_link_5" joint_axis_xyz="${joint_5_axis_xyz}" joint_origin_xyz="${joint_5_origin_xyz}" joint_origin_rpy="${joint_5_origin_rpy}" joint_lower_limit="0" joint_upper_limit="0" joint_velocity_limit="0" joint_torque_limit="0" fixed="true"/>

            <xacro:kinova_armlink link_name="${prefix}_link_5" link_mesh="${link_5_mesh}" use_ring_mesh="true" ring_mesh="ring_small" mesh_no="${link_5_mesh_no}"/>
            <xacro:kinova_armjoint joint_name="${prefix}_joint_5" type="${joint_5_type}" parent="${prefix}_virtual_link_5" child="${prefix}_link_5" joint_axis_xyz="${joint_5_axis_xyz}" joint_origin_xyz="0 0 0" joint_origin_rpy="0 0 ${J5_offset}" joint_lower_limit="${joint_5_lower_limit-J5_offset}" joint_upper_limit="${joint_5_upper_limit-J5_offset}" joint_velocity_limit="${joint_5_velocity_limit}" joint_torque_limit="${joint_5_torque_limit}" interface="${interface}"/>
        </xacro:unless>

        <xacro:if value="${J6_offset in [0.0, 0, None]}">
            <xacro:kinova_armlink link_name="${prefix}_link_6" link_mesh="${link_6_mesh}" use_ring_mesh="true" ring_mesh="ring_small" mesh_no="${link_6_mesh_no}"/>
            <xacro:kinova_armjoint joint_name="${prefix}_joint_6" type="${joint_6_type}" parent="${prefix}_link_5" child="${prefix}_link_6" joint_axis_xyz="${joint_6_axis_xyz}" joint_origin_xyz="${joint_6_origin_xyz}" joint_origin_rpy="${joint_6_origin_rpy}" joint_lower_limit="${joint_6_lower_limit-J6_offset}" joint_upper_limit="${joint_6_upper_limit-J6_offset}" joint_velocity_limit="${joint_6_velocity_limit}" joint_torque_limit="${joint_6_torque_limit}" interface="${interface}"/>
        </xacro:if>

        <xacro:unless value="${J6_offset in [0.0, 0, None]}">
            <xacro:kinova_armlink link_name="${prefix}_virtual_link_6" link_mesh="None" use_ring_mesh="true" ring_mesh="ring_small" mesh_no="${link_6_mesh_no}"/>
            <xacro:kinova_armjoint joint_name="${prefix}_joint_5_to_6" type="fixed" parent="${prefix}_link_5" child="${prefix}_virtual_link_6" joint_axis_xyz="${joint_6_axis_xyz}" joint_origin_xyz="${joint_6_origin_xyz}" joint_origin_rpy="${joint_6_origin_rpy}" joint_lower_limit="0" joint_upper_limit="0" joint_velocity_limit="0" joint_torque_limit="0" fixed="true"/>

            <xacro:kinova_armlink link_name="${prefix}_link_6" link_mesh="${link_6_mesh}" use_ring_mesh="true" ring_mesh="ring_small" mesh_no="${link_6_mesh_no}"/>
            <xacro:kinova_armjoint joint_name="${prefix}_joint_6" type="${joint_6_type}" parent="${prefix}_virtual_link_6" child="${prefix}_link_6" joint_axis_xyz="${joint_6_axis_xyz}" joint_origin_xyz="0 0 0" joint_origin_rpy="0.0 0.0 ${J6_offset}" joint_lower_limit="${joint_6_lower_limit-J6_offset}" joint_upper_limit="${joint_6_upper_limit-J6_offset}" joint_velocity_limit="${joint_6_velocity_limit}" joint_torque_limit="${joint_6_torque_limit}" interface="${interface}"/>
        </xacro:unless>


        <xacro:unless value="${color == 'None'}">
            <xacro:gazebo_materials prefix="${prefix}" color="${color}"/>
        </xacro:unless>

        <xacro:kinova_virtual_link link_name="${prefix}_end_effector"/>
        <xacro:kinova_virtual_joint joint_name="${prefix}_joint_end_effector" type="${joint_end_effector_type}" parent="${prefix}_link_6" child="${prefix}_end_effector" joint_axis_xyz="${joint_end_effector_axis_xyz}" joint_origin_xyz="${joint_end_effector_origin_xyz}" joint_origin_rpy="${joint_end_effector_origin_rpy}" joint_lower_limit="0" joint_upper_limit="0"/>
        <xacro:kinova_2fingers link_hand="${prefix}_link_6" prefix="${prefix}_" fixed="true"/>
    </xacro:macro>



</root>
